### PR TITLE
feat: [MOBI-1105] expose option to add py.typed marker

### PR DESCRIPTION
**Pull request by j-krose**

### CODE REVIEW

**Review by sebasv — APPROVED** [review]
This works for me, although I think this is not a good fit for more "advanced" project setups (ie multiple packages under one pyproject.toml). Isn't it easier to just add the marker as a file permanently in the git repository?

**Comment by j-krose** [comment]
@sebasv Maybe that is the right way to go indeed... @DonDebonair do you think it makes sense here or people should just put it in their repo?

**Comment by j-krose** [comment]
@DonDebonair and @sebasv agree: this should just be a file in the repo, not a CD action.

**Comment by j-krose** [comment]
Closing this PR: @DonDebonair and @sebasv agree: this should just be a file in the repo, not a CD action.

**Pull request closed without merging**
